# Generated by Django 5.0.1 on 2024-06-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='diffs',
            field=models.TextField(default=''),
        ),
    ]
