# Generated by Django 5.0.1 on 2025-02-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0002_archive_diffs'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='engine',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='archive',
            name='prompt',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='archive',
            name='temp',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
