# Generated by Django 5.0.1 on 2025-02-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0004_rename_prompt_archive_edit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='custom_prompt',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
