# Generated by Django 6.1.1 on 2026-09-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0005_archive_custom_prompt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='temp',
        ),
    ]
