# Generated by Django 6.1.1 on 2026-09-07 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0006_remove_archive_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='language_model',
        ),
    ]
