# Generated by Django 6.1.1 on 2026-09-09 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copyeditor', '0007_remove_archive_language_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='key',
        ),
    ]
